# Generated by Django 3.2.9 on 2021-11-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_controller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='remainder',
        ),
        migrations.AddField(
            model_name='activity',
            name='amount',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
