# Generated by Django 3.2.9 on 2021-11-25 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse_controller', '0002_auto_20211125_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(default=None, max_length=10, verbose_name=(('Restock', 'Restock'), ('Transact', 'Transact'), ('Edit', 'Edit'))),
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actual_amount', models.FloatField()),
                ('sold_at', models.FloatField()),
                ('sold_to', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=300)),
                ('item_count', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('sold_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
